# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ZUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 701))
        self.label.setStyleSheet("background-color: rgb(54, 54, 54);\n"
"border-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 561, 631))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255,20%);\n"
"border-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.cal_exit = QtWidgets.QPushButton(self.centralwidget)
        self.cal_exit.setGeometry(QtCore.QRect(530, 20, 40, 30))
        self.cal_exit.setStyleSheet("background-color: rgb(255, 255, 255,0%);")
        self.cal_exit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cal_exit.setIcon(icon)
        self.cal_exit.setIconSize(QtCore.QSize(40, 30))
        self.cal_exit.setObjectName("cal_exit")
        self.cal_minimize = QtWidgets.QPushButton(self.centralwidget)
        self.cal_minimize.setGeometry(QtCore.QRect(480, 20, 40, 30))
        self.cal_minimize.setStyleSheet("background-color: rgb(255, 255, 255,0%);")
        self.cal_minimize.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/minus-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cal_minimize.setIcon(icon1)
        self.cal_minimize.setIconSize(QtCore.QSize(40, 30))
        self.cal_minimize.setObjectName("cal_minimize")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(180, 20, 40, 30))
        self.pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255,0%);\n"
"color: rgb(0, 255, 255);\n"
"font: 75 12pt \"8514oem\";")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/calculator.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(40, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 20, 111, 30))
        self.label_3.setStyleSheet("font: 75 12pt \"8514oem\";\n"
"color: rgb(0, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(60, 80, 461, 51))
        self.label_4.setStyleSheet("font: 75 12pt \"8514oem\";\n"
"background-color: rgb(255, 255, 255,30%);\n"
"border-radius:10px;")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 130, 561, 561))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.butt_C = QtWidgets.QPushButton(self.frame)
        self.butt_C.setGeometry(QtCore.QRect(40, 30, 90, 40))
        self.butt_C.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 0, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"")
        self.butt_C.setObjectName("butt_C")
        self.butt_sin = QtWidgets.QPushButton(self.frame)
        self.butt_sin.setGeometry(QtCore.QRect(170, 30, 90, 40))
        self.butt_sin.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 85, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"")
        self.butt_sin.setObjectName("butt_sin")
        self.butt_cos = QtWidgets.QPushButton(self.frame)
        self.butt_cos.setGeometry(QtCore.QRect(290, 30, 90, 40))
        self.butt_cos.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 85, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"")
        self.butt_cos.setObjectName("butt_cos")
        self.butt_tan = QtWidgets.QPushButton(self.frame)
        self.butt_tan.setGeometry(QtCore.QRect(410, 30, 90, 40))
        self.butt_tan.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 85, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"")
        self.butt_tan.setObjectName("butt_tan")
        self.butt_openbrac = QtWidgets.QPushButton(self.frame)
        self.butt_openbrac.setGeometry(QtCore.QRect(40, 110, 90, 40))
        self.butt_openbrac.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_openbrac.setObjectName("butt_openbrac")
        self.butt_closebrac = QtWidgets.QPushButton(self.frame)
        self.butt_closebrac.setGeometry(QtCore.QRect(170, 110, 90, 40))
        self.butt_closebrac.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_closebrac.setObjectName("butt_closebrac")
        self.butt_divide = QtWidgets.QPushButton(self.frame)
        self.butt_divide.setGeometry(QtCore.QRect(410, 110, 90, 40))
        self.butt_divide.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"\n"
"}")
        self.butt_divide.setObjectName("butt_divide")
        self.butt_clearlastnum = QtWidgets.QPushButton(self.frame)
        self.butt_clearlastnum.setGeometry(QtCore.QRect(290, 110, 90, 40))
        self.butt_clearlastnum.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_clearlastnum.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Icons/left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.butt_clearlastnum.setIcon(icon3)
        self.butt_clearlastnum.setIconSize(QtCore.QSize(40, 30))
        self.butt_clearlastnum.setObjectName("butt_clearlastnum")
        self.butt_8 = QtWidgets.QPushButton(self.frame)
        self.butt_8.setGeometry(QtCore.QRect(170, 190, 90, 40))
        self.butt_8.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_8.setObjectName("butt_8")
        self.butt_5 = QtWidgets.QPushButton(self.frame)
        self.butt_5.setGeometry(QtCore.QRect(170, 270, 90, 40))
        self.butt_5.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_5.setObjectName("butt_5")
        self.butt_6 = QtWidgets.QPushButton(self.frame)
        self.butt_6.setGeometry(QtCore.QRect(40, 270, 90, 40))
        self.butt_6.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_6.setObjectName("butt_6")
        self.butt_7 = QtWidgets.QPushButton(self.frame)
        self.butt_7.setGeometry(QtCore.QRect(290, 190, 90, 40))
        self.butt_7.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_7.setObjectName("butt_7")
        self.butt_9 = QtWidgets.QPushButton(self.frame)
        self.butt_9.setGeometry(QtCore.QRect(40, 190, 90, 40))
        self.butt_9.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_9.setObjectName("butt_9")
        self.butt_minus = QtWidgets.QPushButton(self.frame)
        self.butt_minus.setGeometry(QtCore.QRect(410, 270, 90, 40))
        self.butt_minus.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"\n"
"}")
        self.butt_minus.setObjectName("butt_minus")
        self.butt_multiply = QtWidgets.QPushButton(self.frame)
        self.butt_multiply.setGeometry(QtCore.QRect(410, 190, 90, 40))
        self.butt_multiply.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"\n"
"}")
        self.butt_multiply.setObjectName("butt_multiply")
        self.Butt_3 = QtWidgets.QPushButton(self.frame)
        self.Butt_3.setGeometry(QtCore.QRect(40, 350, 90, 40))
        self.Butt_3.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.Butt_3.setObjectName("Butt_3")
        self.Butt_dot = QtWidgets.QPushButton(self.frame)
        self.Butt_dot.setGeometry(QtCore.QRect(290, 430, 90, 40))
        self.Butt_dot.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.Butt_dot.setObjectName("Butt_dot")
        self.butt_plus = QtWidgets.QPushButton(self.frame)
        self.butt_plus.setGeometry(QtCore.QRect(410, 350, 90, 40))
        self.butt_plus.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"\n"
"}")
        self.butt_plus.setObjectName("butt_plus")
        self.butt_1 = QtWidgets.QPushButton(self.frame)
        self.butt_1.setGeometry(QtCore.QRect(290, 350, 90, 40))
        self.butt_1.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_1.setObjectName("butt_1")
        self.Butt_0 = QtWidgets.QPushButton(self.frame)
        self.Butt_0.setGeometry(QtCore.QRect(170, 430, 90, 40))
        self.Butt_0.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.Butt_0.setObjectName("Butt_0")
        self.butt_00 = QtWidgets.QPushButton(self.frame)
        self.butt_00.setGeometry(QtCore.QRect(40, 430, 90, 40))
        self.butt_00.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_00.setObjectName("butt_00")
        self.butt_2 = QtWidgets.QPushButton(self.frame)
        self.butt_2.setGeometry(QtCore.QRect(170, 350, 90, 40))
        self.butt_2.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_2.setObjectName("butt_2")
        self.butt_4 = QtWidgets.QPushButton(self.frame)
        self.butt_4.setGeometry(QtCore.QRect(290, 270, 90, 40))
        self.butt_4.setStyleSheet("QPushButton{\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 75 12pt \"8514oem\";\n"
"border:2px solid black;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.butt_4.setObjectName("butt_4")
        self.butt_equal = QtWidgets.QPushButton(self.frame)
        self.butt_equal.setGeometry(QtCore.QRect(410, 430, 90, 40))
        self.butt_equal.setStyleSheet("QPushButton{\n"
"background-color: rgb(0, 0, 255);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"background-color: rgb(0, 255, 0);\n"
"font: 26pt \"Algerian\";\n"
"border:2px solid black;\n"
"\n"
"}")
        self.butt_equal.setObjectName("butt_equal")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(430, 520, 121, 31))
        self.label_6.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.label_6.setObjectName("label_6")
        self.erroe_show = QtWidgets.QLabel(self.frame)
        self.erroe_show.setGeometry(QtCore.QRect(70, 490, 291, 31))
        self.erroe_show.setStyleSheet("font: 8pt \"8514oem\";\n"
"color: rgb(255, 0, 0);")
        self.erroe_show.setText("")
        self.erroe_show.setAlignment(QtCore.Qt.AlignCenter)
        self.erroe_show.setObjectName("erroe_show")
        self.number_show_text = QtWidgets.QLabel(self.centralwidget)
        self.number_show_text.setGeometry(QtCore.QRect(70, 80, 431, 51))
        self.number_show_text.setStyleSheet("font: 75 12pt \"8514oem\";")
        self.number_show_text.setText("")
        self.number_show_text.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.number_show_text.setObjectName("number_show_text")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Calculator"))
        self.butt_C.setText(_translate("MainWindow", "C"))
        self.butt_sin.setText(_translate("MainWindow", "sin"))
        self.butt_cos.setText(_translate("MainWindow", "cos"))
        self.butt_tan.setText(_translate("MainWindow", "tan"))
        self.butt_openbrac.setText(_translate("MainWindow", "("))
        self.butt_closebrac.setText(_translate("MainWindow", ")"))
        self.butt_divide.setText(_translate("MainWindow", "/"))
        self.butt_8.setText(_translate("MainWindow", "8"))
        self.butt_5.setText(_translate("MainWindow", "5"))
        self.butt_6.setText(_translate("MainWindow", "6"))
        self.butt_7.setText(_translate("MainWindow", "7"))
        self.butt_9.setText(_translate("MainWindow", "9"))
        self.butt_minus.setText(_translate("MainWindow", "-"))
        self.butt_multiply.setText(_translate("MainWindow", "*"))
        self.Butt_3.setText(_translate("MainWindow", "3"))
        self.Butt_dot.setText(_translate("MainWindow", "."))
        self.butt_plus.setText(_translate("MainWindow", "+"))
        self.butt_1.setText(_translate("MainWindow", "1"))
        self.Butt_0.setText(_translate("MainWindow", "0"))
        self.butt_00.setText(_translate("MainWindow", "00"))
        self.butt_2.setText(_translate("MainWindow", "2"))
        self.butt_4.setText(_translate("MainWindow", "4"))
        self.butt_equal.setText(_translate("MainWindow", "="))
        self.label_6.setText(_translate("MainWindow", "Version 1.0"))
